---
- name: Install python if needed for Ansible
  import_playbook: install_python.yml
- hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Check for pip
      raw: test -e /usr/bin/pip
      changed_when: false
      failed_when: false
      register: check_pip

    - name: Install pip
      apt: name=python-pip state=present
      when: check_pip.rc != 0

    - name: Check for docker pip
      raw: pip show docker
      changed_when: false
      failed_when: false
      register: check_docker_pip

    - name: install docker pip package
      pip: name=docker
      when: check_docker_pip.rc != 0

    - name: check for docker
      raw: test -e /usr/bin/docker
      changed_when: false
      failed_when: false
      register: check_docker

    - name: install docker
      raw: curl https://get.docker.com/ | bash
      when: check_docker.rc != 0

    - name: Run docker image with options
      docker_container:
        name: app
        image: roottjnii/interview-container:201805
        restart_policy: unless-stopped
        published_ports: 
          - 4567:4567
        
        